/**
 * ATTRIBUTION AGENT - Generate Attribution
 * Agent 6 of 7 in the D2A Pipeline
 * 
 * PURPOSE: Commons Good credits compilation for all services used
 * 
 * INPUT: { projectId, curated_file, music_file, video_file }
 * OUTPUT: { credits[], license, commonsGood, markdown }
 */

import type { Handler, HandlerEvent, HandlerContext } from "@netlify/functions";

interface AttributionRequest {
  projectId: string;
  curated_file?: string;
  music_file?: string;
  video_file?: string;
  services?: string[];
}

interface Credit {
  service: string;
  type: 'ai' | 'media' | 'platform' | 'human';
  description: string;
  license: string;
  url?: string;
}

interface AttributionResponse {
  success: boolean;
  projectId: string;
  credits: Credit[];
  license: string;
  commonsGood: string;
  markdown: string;
  generatedAt: string;
}

/**
 * Standard credits for services used in the pipeline
 */
const SERVICE_CREDITS: Record<string, Credit> = {
  openai: {
    service: 'OpenAI GPT-4',
    type: 'ai',
    description: 'Narrative script generation',
    license: 'OpenAI Terms of Use',
    url: 'https://openai.com',
  },
  elevenlabs: {
    service: 'ElevenLabs',
    type: 'ai',
    description: 'Voice synthesis and narration',
    license: 'ElevenLabs Terms of Service',
    url: 'https://elevenlabs.io',
  },
  suno: {
    service: 'Suno AI',
    type: 'ai',
    description: 'Original music composition',
    license: 'Suno Terms of Service',
    url: 'https://suno.ai',
  },
  ffmpeg: {
    service: 'FFmpeg',
    type: 'platform',
    description: 'Video compilation and processing',
    license: 'LGPL/GPL',
    url: 'https://ffmpeg.org',
  },
  netlify: {
    service: 'Netlify',
    type: 'platform',
    description: 'Serverless hosting and functions',
    license: 'Netlify Terms of Service',
    url: 'https://netlify.com',
  },
  sirtrav: {
    service: 'SirTrav A2A Studio',
    type: 'platform',
    description: 'D2A Pipeline orchestration',
    license: 'MIT',
    url: 'https://github.com/WSP001/SirTrav-A2A-Studio',
  },
};

/**
 * Generate markdown credits
 */
function generateMarkdown(credits: Credit[], projectId: string): string {
  let md = `# Credits - ${projectId}\n\n`;
  md += `*Generated by SirTrav A2A Studio*\n\n`;
  md += `## For the Commons Good 🌍\n\n`;
  md += `This project was created using open and AI-powered tools, attributed below.\n\n`;
  md += `---\n\n`;
  
  const byType: Record<string, Credit[]> = {};
  credits.forEach(c => {
    if (!byType[c.type]) byType[c.type] = [];
    byType[c.type].push(c);
  });
  
  const typeLabels: Record<string, string> = {
    ai: '🤖 AI Services',
    platform: '🛠️ Platforms & Tools',
    media: '📷 Media Sources',
    human: '👤 Human Contributors',
  };
  
  for (const [type, typeCredits] of Object.entries(byType)) {
    md += `### ${typeLabels[type] || type}\n\n`;
    for (const credit of typeCredits) {
      md += `- **${credit.service}**: ${credit.description}`;
      if (credit.url) md += ` ([link](${credit.url}))`;
      md += `\n`;
      md += `  - License: ${credit.license}\n`;
    }
    md += `\n`;
  }
  
  md += `---\n\n`;
  md += `*Attribution generated on ${new Date().toISOString()}*\n`;
  
  return md;
}

const handler: Handler = async (event: HandlerEvent, context: HandlerContext) => {
  console.log('📜 ATTRIBUTION AGENT - Generate Attribution');
  
  const headers = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Content-Type': 'application/json',
  };
  
  if (event.httpMethod === 'OPTIONS') {
    return { statusCode: 200, headers, body: '' };
  }
  
  if (event.httpMethod !== 'POST') {
    return {
      statusCode: 405,
      headers,
      body: JSON.stringify({ error: 'Method not allowed' }),
    };
  }
  
  try {
    const request: AttributionRequest = JSON.parse(event.body || '{}');
    
    if (!request.projectId) {
      return {
        statusCode: 400,
        headers,
        body: JSON.stringify({ error: 'projectId is required' }),
      };
    }
    
    // Collect credits based on services used
    const usedServices = request.services || ['openai', 'elevenlabs', 'suno', 'ffmpeg', 'netlify', 'sirtrav'];
    const credits: Credit[] = usedServices
      .filter(s => SERVICE_CREDITS[s])
      .map(s => SERVICE_CREDITS[s]);
    
    // Generate markdown
    const markdown = generateMarkdown(credits, request.projectId);
    
    const response: AttributionResponse = {
      success: true,
      projectId: request.projectId,
      credits,
      license: 'CC BY-SA 4.0',
      commonsGood: 'This work is shared for the Commons Good. Please attribute all contributors.',
      markdown,
      generatedAt: new Date().toISOString(),
    };
    
    console.log(`✅ Generated attribution with ${credits.length} credits`);
    
    return {
      statusCode: 200,
      headers,
      body: JSON.stringify(response),
    };
    
  } catch (error) {
    console.error('❌ Attribution Agent error:', error);
    return {
      statusCode: 500,
      headers,
      body: JSON.stringify({ 
        success: false, 
        error: error instanceof Error ? error.message : 'Unknown error' 
      }),
    };
  }
};

export { handler };
