steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sirtrav-studio:$COMMIT_SHA', '-f', 'gcp/Dockerfile', '.']

  # 2. Push the container image to Container Registry/Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sirtrav-studio:$COMMIT_SHA']

  # 3. Deploy container to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sirtrav-studio'
      - '--image'
      - 'gcr.io/$PROJECT_ID/sirtrav-studio:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # WARNING: Secure this in production!

images:
  - 'gcr.io/$PROJECT_ID/sirtrav-studio:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
